services:
  hockey-clipper-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_ADDRESS: "https://api.clip.jh1236.top"
    image: hockey-clipper-frontend
    container_name: hockey-clipper-frontend-container
    ports:
      - "8081:3000"
    environment:
      NODE_ENV: production
      PORT: "3000"
    restart: unless-stopped
  hockey-clipper-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - db:/database
      - cache:/cache
      - videos:/videos
    image: hockey-clipper-backend
    container_name: hockey-clipper-backend-container
    env_file:
      - ./backend/livehockey.env
      - ./backend/whistleiq.env
    environment:
      ADDRESS: "https://api.clip.jh1236.top"
      CACHE_DIRECTORY: '/cache'
      VIDEO_DIRECTORY: '/videos'
      DATABASE_PATH: '/database/database.db'
    ports:
      - "5003:5000"
    restart: unless-stopped

volumes:
  db:
  cache:
  videos: