import {SqliteConnection} from "ts-sql-query/connections/SqliteConnection";
import {SqliteDateTimeFormat, SqliteDateTimeFormatType} from "ts-sql-query/connections/SqliteConfiguration";
import {Table} from "ts-sql-query/Table";
import sqlite from 'sqlite3'
import {Sqlite3QueryRunner} from "ts-sql-query/queryRunners/Sqlite3QueryRunner";

class DBConnection extends SqliteConnection<'DBConnection'> {
    protected uuidStrategy = 'string' as const

    protected getDateTimeFormat(_type: SqliteDateTimeFormatType): SqliteDateTimeFormat {
        return 'UTC as text'
    }

}

export const tGames = new class TGames extends Table<DBConnection, 'TGames'> {
    id = this.autogeneratedPrimaryKey('id', 'int');
    blob = this.column('blob', 'string');
    teamOne = this.column('team_one', 'string');
    teamTwo = this.column('team_two', 'string');
    teamOneImage = this.column('team_one_image', 'string');
    teamTwoImage = this.column('team_two_image', 'string');
    competitionName = this.column('competition_name', 'string');

    constructor() {
        super('games'); // table name in the database
    }
}()

export const tClips = new class TClips extends Table<DBConnection, 'TClips'> {
    id = this.autogeneratedPrimaryKey('id', 'int');
    gameId = this.column('game_id', 'int');
    name = this.column('name', 'string');
    startTime = this.optionalColumn('start_time', 'int');
    duration = this.column('duration', 'int');
    link = this.column('link', 'string');
    comment = this.optionalColumn('comment', 'string');

    constructor() {
        super('clips'); // table name in the database
    }
}()

const db = new sqlite.Database('./resources/database.db');

export async function getDbSession() {
    const connection = new DBConnection(new Sqlite3QueryRunner(db))
    await connection.beginTransaction()
    return {
        connection: connection,
        [Symbol.asyncDispose]: async () => {
            await connection.commit()
        }
    }
}