import {SqliteConnection} from "ts-sql-query/connections/SqliteConnection";
import {SqliteDateTimeFormat, SqliteDateTimeFormatType} from "ts-sql-query/connections/SqliteConfiguration";
import {Table} from "ts-sql-query/Table";
import sqlite from 'sqlite3'
import {Sqlite3QueryRunner} from "ts-sql-query/queryRunners/Sqlite3QueryRunner";

class DBConnection extends SqliteConnection<'DBConnection'> {
    protected uuidStrategy = 'string' as const

    protected getDateTimeFormat(_type: SqliteDateTimeFormatType): SqliteDateTimeFormat {
        return 'UTC as text'
    }

}

export interface Game {
    blob: string
    teamOne: string
    teamTwo: string
    teamOneLongName: string
    teamTwoLongName: string
    teamOneImage: string
    teamTwoImage: string
    competitionName: string
    startTime: number
    lastServerPing: number
    isLive: boolean
    altiusLink?: string
    teamstarLink?: string
}

export const tGames = new class TGames extends Table<DBConnection, 'TGames'> {
    id = this.autogeneratedPrimaryKey('id', 'int');
    blob = this.column('blob', 'string');
    teamOne = this.column('team_one', 'string');
    teamTwo = this.column('team_two', 'string');
    teamOneLongName = this.column('team_one_long_name', 'string');
    teamTwoLongName = this.column('team_two_long_name', 'string');
    teamOneImage = this.column('team_one_image', 'string');
    teamTwoImage = this.column('team_two_image', 'string');
    competitionName = this.column('competition_name', 'string');
    startTime = this.column('start_time', 'int')
    lastServerPing = this.column('last_server_ping', 'int')
    timeCreated = this.columnWithDefaultValue('time_created', 'int')
    isLive = this.column('is_live', 'boolean')
    altiusLink = this.optionalColumn('altius_link', 'string')
    teamstarLink = this.optionalColumn('teamstar_link', 'string')

    constructor() {
        super('games'); // table name in the database
    }
}()

export const tClips = new class TClips extends Table<DBConnection, 'TClips'> {
    id = this.autogeneratedPrimaryKey('id', 'int');
    gameId = this.column('game_id', 'int');
    name = this.column('name', 'string');
    startTime = this.optionalColumn('start_time', 'int');
    duration = this.column('duration', 'int');
    link = this.column('link', 'string');
    comment = this.optionalColumn('comment', 'string');
    timeCreated = this.columnWithDefaultValue('time_created', 'int')

    constructor() {
        super('clips'); // table name in the database
    }
}()

export const tImages = new class TImages extends Table<DBConnection, 'TImages'> {
    id = this.autogeneratedPrimaryKey('id', 'int');
    name = this.column('name', 'string');
    link = this.column('link', 'string');
    timeCreated = this.columnWithDefaultValue('time_created', 'int')

    constructor() {
        super('images'); // table name in the database
    }
}()

export const tUsers = new class TUsers extends Table<DBConnection, 'TUsers'> {
    id = this.autogeneratedPrimaryKey('id', 'int');
    username = this.column('username', 'string');
    token = this.column('token', 'string');

    constructor() {
        super('users'); // table name in the database
    }
}()

const db = new sqlite.Database('./resources/database.db');

export async function getDbSession() {
    return new DBConnection(new Sqlite3QueryRunner(db))
}